version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: rodriguezjared/geoserver:part1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 600M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet:


